// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75EZ3ikG8TgLCq8HKBrzjWYsv2eacGjg',
    appId: '1:131136834751:web:ce8c3d63608c0ef42f0a0a',
    messagingSenderId: '131136834751',
    projectId: 'cv-builder-79690',
    authDomain: 'cv-builder-79690.firebaseapp.com',
    databaseURL: 'https://cv-builder-79690-default-rtdb.firebaseio.com',
    storageBucket: 'cv-builder-79690.appspot.com',
    measurementId: 'G-VFHFRQ06PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKYMblhI4MWzFQM7tLuiHDY3m_BsPsKw',
    appId: '1:131136834751:android:6b2cf73f006a70d52f0a0a',
    messagingSenderId: '131136834751',
    projectId: 'cv-builder-79690',
    databaseURL: 'https://cv-builder-79690-default-rtdb.firebaseio.com',
    storageBucket: 'cv-builder-79690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdApRYkxCki_yxtn3R6YjoKEquhIjt0Mk',
    appId: '1:131136834751:ios:bcec562baed7bc2a2f0a0a',
    messagingSenderId: '131136834751',
    projectId: 'cv-builder-79690',
    databaseURL: 'https://cv-builder-79690-default-rtdb.firebaseio.com',
    storageBucket: 'cv-builder-79690.appspot.com',
    iosBundleId: 'com.example.cvBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdApRYkxCki_yxtn3R6YjoKEquhIjt0Mk',
    appId: '1:131136834751:ios:bcec562baed7bc2a2f0a0a',
    messagingSenderId: '131136834751',
    projectId: 'cv-builder-79690',
    databaseURL: 'https://cv-builder-79690-default-rtdb.firebaseio.com',
    storageBucket: 'cv-builder-79690.appspot.com',
    iosBundleId: 'com.example.cvBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA75EZ3ikG8TgLCq8HKBrzjWYsv2eacGjg',
    appId: '1:131136834751:web:b3ac38180e36be3b2f0a0a',
    messagingSenderId: '131136834751',
    projectId: 'cv-builder-79690',
    authDomain: 'cv-builder-79690.firebaseapp.com',
    databaseURL: 'https://cv-builder-79690-default-rtdb.firebaseio.com',
    storageBucket: 'cv-builder-79690.appspot.com',
    measurementId: 'G-DQCGTMMJFE',
  );
}
